version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - TZ=America/Montreal
      - PGID=100
      - PUID=1038
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/data/docker/radarr/config:/config
      - /volume1/data/downloads:/downloads
      - /volume1/data/downloads/radarr:/movies
      - /volume1/data/downloads/radarr:/volume1/data/downloads/radarr
    restart: unless-stopped
    mem_limit: 350m
    network_mode: bridge
