version: "2.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - TZ=America/Montreal
      - PGID=100
      - PUID=1036
      - RUN_OPTS=--ProxyConnection=172.17.0.1:8118
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/data/docker/jackett/config:/config
      - /volume1/data/downloads/watch:/downloads
    restart: unless-stopped
    mem_limit: 350m
    network_mode: bridge
