version: "2.1"
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    ports:
      - "6789:6789"
    environment:
      - TZ=America/Montreal
      - PGID=100
      - PUID=1047
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/data/docker/nzbget/config:/config
      - /volume1/data/downloads:/downloads
    restart: unless-stopped
    mem_limit: 350m
    network_mode: bridge
