version: "2.1"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    ports:
      - "8686:8686"
    environment:
      - TZ=America/Montreal
      - PGID=100
      - PUID=1041
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/data/docker/lidarr/config:/config
      - /volume1/data/downloads/music:/downloads
      - /volume1/data/music:/music
    restart: unless-stopped
    mem_limit: 350m
    network_mode: bridge
