version: "2.4"
services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    hostname: "pi.hole"
    #mac_address: b1:51:09:fd:b1:73
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      - TZ=America/Montreal
      - VIRTUAL_HOST=pi.hole
      - PROXY_LOCATION=pi.hole
      - ServerIP=192.168.0.111
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/data/docker/pihole/config/etc:/etc/pihole/
      - /volume1/data/docker/pihole/config/dnsmasq:/etc/dnsmasq.d/
    restart: unless-stopped
    mem_limit: 350m
    #network_mode: bridge
    networks:
      - pihole_network
networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.111/32

